# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=20)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_mod_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
